name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  bump:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"

  build_linux:
    runs-on: ubuntu-22.04
    needs: bump
    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc-i686-linux-gnu
          sudo apt-get install gcc-multilib
      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          targets: i686-unknown-linux-gnu
      - name: Build 32-bit
        run: cargo build --release --target i686-unknown-linux-gnu
      - name: Strip debug symbols
        run: strip target/i686-unknown-linux-gnu/release/libgmsv_hooktest.so
      - name: Rename binaries
        run: mv target/i686-unknown-linux-gnu/release/libgmsv_hooktest.so target/i686-unknown-linux-gnu/release/gmsv_hooktest_linux.dll
      - name: Release Linux
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.bump.outputs.new_tag }}
          artifacts: target/i686-unknown-linux-gnu/release/gmsv_hooktest_linux.dll

  build_windows:
    runs-on: windows-latest
    needs: bump
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly toolchain
        run: rustup toolchain install nightly
      - name: Add targets
        run: rustup target add i686-pc-windows-msvc
      - name: Build 32-bit
        run: cargo build --release --target i686-pc-windows-msvc
      - name: Rename binaries
        run: mv target/i686-pc-windows-msvc/release/gmsv_hooktest.dll target/i686-pc-windows-msvc/release/gmsv_hooktest_win32.dll
      - name: Release Windows
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.bump.outputs.new_tag }}
          artifacts: target/i686-pc-windows-msvc/release/gmsv_hooktest_win32.dll
